---
name: Lint cmake-format

on:
  push:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  # CMake Format
  cmake-format-linter:
    name: Lint Code Base (cmake-format-lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false

      - name: Format CMake files
        id: cmake-format
        uses: PuneetMatharu/cmake-format-lint-action@4ed77e1b4e9ae7b072e4e34c54461316771566c9
        with:
          args: --config-files ./github/linters/cmake-format.yaml
