---
name: Lint Code Base

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  super-linter:
    name: Lint Code Base (super-linter)
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Lint Code Base
        # yamllint disable-line
        uses: docker://ghcr.io/super-linter/super-linter@sha256:857dcc3f0bf5dd065fdeed1ace63394bb2004238a5ef02910ea23d9bcd8fd2b8 # v8.5.0-slim
        env:
          VALIDATE_CPP: false # Use clang-format instead
          VALIDATE_ANSIBLE: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          FIX_MARKDOWN_PRETTIER: true
          FIX_YAML_PRETTIER: true
          FIX_JSON_PRETTIER: true
          FIX_SHELL_SHFMT: true
          FIX_CLANG_FORMAT: true
          FIX_PYTHON_RUFF_FORMAT: true
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          DEFAULT_BRANCH: origin/develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
